tasks:
  - init: npm install
image:
  file: .gitpod.Dockerfile

vscode:
  extensions:
    - bajdzis.vscode-database@2.2.0:KaEYYfe8G3NOWlsM6VNLHA==
    - GreatMinds.gitflow4code@1.2.3:zHGKNb8OWRw8BpiZbGQsTw==
    - donjayamanne.git-extension-pack@0.1.3:SfFwfST7Hdp+r/KRulDGXA==